name: pyalcs-experiments
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyter=1.0.0
  - jupyterlab>=2.0.0
  - jupyter_contrib_nbextensions>=0.5.1
  - mlflow>=1.7
  - pandas>=1.0.0
  - papermill>=2.0.0
  - matplotlib>=3.1.1
  - pytest>=5.4
  - pip
  - dill
  - pip:
    - gym==0.11
    - "-e git+https://github.com/ParrotPrediction/pyalcs.git@1d6b794e730f22c5c93a78b7aa4d43d75350e41c#egg=parrotprediction-pyalcs"
    - "-e git+https://github.com/ParrotPrediction/openai-envs.git@d20d24d2a52c0cc01e24613ba5a49b1d781da413#egg=parrotprediction-openai-envs"
