name: pyalcs-experiments
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyter=1.0.0
  - jupyterlab>=3.2.0
  - jupyter_contrib_nbextensions>=0.5.1
  - mlflow>=1.7
  - pandas>=1.0.0
  - papermill>=2.0.0
  - matplotlib>=3.1.1
  - pytest>=5.4
  - pip
  - dill
  - ipympl
  - tqdm
  - pip:
    - gym>=0.18
  imports:
    - requirements/base.
