name: pyalcs-rmpx-hashing

channels:
  - conda-forge

dependencies:
  - python=3.7
  - mlflow
  - pip
  - pip:
    - "-e git+https://github.com/ParrotPrediction/pyalcs.git@2.0.2#egg=pyalcs[mlflow]"
    - "-e git+https://github.com/ParrotPrediction/openai-envs.git@1f9d0f6249a9ccddc3299309d72687fbcbb53fc6#egg=parrotprediction-openai-envs"
